import '../models/friend_post_data.dart';

/// 친구 찾기 게시글 더미 데이터
final List<Map<String, dynamic>> dummyFriendPosts = [
  {
    'id': 'friend_1',
    'user_name': '테스트 사용자 A',
    'date': '1시간 전',
    'title': '오늘 저녁 같이 먹을 사람?',
    'store_name': '학교 앞 한식당',
    'meeting_place': '캠퍼스 공용 모임 장소 A',
    'current_people': 2,
    'max_people': 4,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(hours: 2)).toIso8601String(),
    'meeting_latitude': 37.567,
    'meeting_longitude': 126.978,
  },
  {
    'id': 'friend_2',
    'user_name': '테스트 사용자 B',
    'date': '3시간 전',
    'title': '점심 같이 먹어요~',
    'store_name': '학생식당',
    'meeting_place': '캠퍼스 공용 모임 장소 B',
    'current_people': 1,
    'max_people': 3,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(hours: 1)).toIso8601String(),
    'meeting_latitude': 37.567,
    'meeting_longitude': 126.979,
  },
  {
    'id': 'friend_3',
    'user_name': '테스트 사용자 C',
    'date': '45분 전',
    'title': '카페에서 공부하실 분',
    'store_name': '스타벅스',
    'meeting_place': '캠퍼스 공용 모임 장소 C',
    'current_people': 1,
    'max_people': 2,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(minutes: 30)).toIso8601String(),
    'meeting_latitude': 37.568,
    'meeting_longitude': 126.979,
  },
  {
    'id': 'friend_4',
    'user_name': '테스트 사용자 D',
    'date': '어제 20:00',
    'title': '저녁 고기 드실분!!',
    'store_name': '캠퍼스 삼겹살',
    'meeting_place': '캠퍼스 공용 모임 장소 D',
    'current_people': 4,
    'max_people': 4,
    'is_recruiting': false,
    'deadline': DateTime.now().subtract(const Duration(hours: 12)).toIso8601String(),
    'meeting_latitude': 37.566,
    'meeting_longitude': 126.978,
  },
  {
    'id': 'friend_5',
    'user_name': '테스트 사용자 E',
    'date': '20분 전',
    'title': '브런치 같이 먹을 사람 구해요',
    'store_name': '브런치 카페',
    'meeting_place': '캠퍼스 공용 모임 장소 E',
    'current_people': 2,
    'max_people': 5,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(hours: 4)).toIso8601String(),
    'meeting_latitude': 37.567,
    'meeting_longitude': 126.978,
  },
  {
    'id': 'friend_6',
    'user_name': '테스트 사용자 F',
    'date': '5분 전',
    'title': '야식 치킨 같이 먹어요',
    'store_name': 'BBQ치킨',
    'meeting_place': '캠퍼스 공용 모임 장소 F',
    'current_people': 1,
    'max_people': 3,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(hours: 1, minutes: 30)).toIso8601String(),
    'meeting_latitude': 37.567,
    'meeting_longitude': 126.979,
  },
];

/// FriendPost 객체 리스트로 변환
List<FriendPost> getDummyFriendPosts() {
  return dummyFriendPosts.map((json) => FriendPost.fromJson(json)).toList();
}
