import '../models/delivery_post_data.dart';

/// 배달 게시글 더미 데이터
final List<Map<String, dynamic>> dummyDeliveryPosts = [
  {
    'id': 'delivery_1',
    'user_name': '테스트 사용자 A',
    'date': '2시간 전',
    'title': '치킨 같이 시키실 분!',
    'store_name': 'BBQ 황금올리브치킨',
    'delivery_place': '캠퍼스 공용 수령 장소 A',
    'target_price': 20000,
    'current_people': 2,
    'max_people': 4,
    'delivery_fee': 3000,
    'fee_per_person': 750,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(hours: 2)).toIso8601String(),
    'store_latitude': 37.567,
    'store_longitude': 126.978,
    'delivery_latitude': 37.568,
    'delivery_longitude': 126.979,
    'details': '황올 반마리 주문할 예정이에요! 함께 시키시면 배달비 절약할 수 있어요 😊',
  },
  {
    'id': 'delivery_2',
    'user_name': '테스트 사용자 B',
    'date': '30분 전',
    'title': '맥도날드 배달비 나눠요~',
    'store_name': '맥도날드 강남점',
    'delivery_place': '캠퍼스 공용 수령 장소 B',
    'target_price': 15000,
    'current_people': 1,
    'max_people': 3,
    'delivery_fee': 2500,
    'fee_per_person': 833,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(hours: 1)).toIso8601String(),
    'store_latitude': 37.566,
    'store_longitude': 126.978,
    'delivery_latitude': 37.567,
    'delivery_longitude': 126.979,
    'details': null,
  },
  {
    'id': 'delivery_3',
    'user_name': '테스트 사용자 C',
    'date': '1시간 전',
    'title': '피자 2판 시킬건데 같이 하실분',
    'store_name': '도미노피자',
    'delivery_place': '캠퍼스 공용 수령 장소 C',
    'target_price': 35000,
    'current_people': 3,
    'max_people': 5,
    'delivery_fee': 4000,
    'fee_per_person': 800,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(hours: 3)).toIso8601String(),
    'store_latitude': 37.567,
    'store_longitude': 126.979,
    'delivery_latitude': 37.568,
    'delivery_longitude': 126.980,
  },
  {
    'id': 'delivery_4',
    'user_name': '테스트 사용자 D',
    'date': '오늘 12:30',
    'title': '점심 중국집 배달 같이해요',
    'store_name': '홍콩반점',
    'delivery_place': '캠퍼스 공용 수령 장소 D',
    'target_price': 25000,
    'current_people': 4,
    'max_people': 4,
    'delivery_fee': 3500,
    'fee_per_person': 875,
    'is_recruiting': false,
    'deadline': DateTime.now().subtract(const Duration(hours: 1)).toIso8601String(),
    'store_latitude': 37.566,
    'store_longitude': 126.977,
    'delivery_latitude': 37.567,
    'delivery_longitude': 126.978,
  },
  {
    'id': 'delivery_5',
    'user_name': '테스트 사용자 E',
    'date': '10분 전',
    'title': '야식 족발 드실분~~',
    'store_name': '원할머니보쌈족발',
    'delivery_place': '캠퍼스 공용 수령 장소 E',
    'target_price': 30000,
    'current_people': 1,
    'max_people': 4,
    'delivery_fee': 3000,
    'fee_per_person': 750,
    'is_recruiting': true,
    'deadline': DateTime.now().add(const Duration(minutes: 50)).toIso8601String(),
    'store_latitude': 37.567,
    'store_longitude': 126.978,
    'delivery_latitude': 37.568,
    'delivery_longitude': 126.979,
  },
];

/// DeliveryPost 객체 리스트로 변환
List<DeliveryPost> getDummyDeliveryPosts() {
  return dummyDeliveryPosts.map((json) => DeliveryPost.fromJson(json)).toList();
}
